Dim sob
set sob = WScript.CreateObject("Wscript.Shell")

Function GenerateComp( fname, fullstring )
	dim path, cmd
	path = "..\"
	cmd = "Cmd /c copy /b /y "+fullstring+" "+path+fname+".html"
	'sob.popup cmd
	sob.run(cmd)
End Function

'system product family
fname = "bscan"
softprod = "bscan"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + "snip-" + softprod + ".html+"
fullstring = fullstring + ".\" + softprod + "\bscan-family.html+"
fullstring = fullstring + ".\" + softprod + "\snip-label.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-08.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring

'system product
fname = "bscan-bookedge"
softprod = "bscan"
lpath = ".\be\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-be.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\be-01.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-08.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-ill-overview.html+"
fullstring = fullstring + lpath + "snip-ill-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-ill-doc.html+"
fullstring = fullstring + lpath + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring

'system product
fname = "bscan-bookeye4v1"
softprod = "bscan"
lpath = ".\be4v1\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-be4.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-08.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-ill-overview.html+"
fullstring = fullstring + lpath + "snip-ill-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-ill-doc.html+"
fullstring = fullstring + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring

'system product
fname = "bscan-bookeye4v2"
softprod = "bscan"
lpath = ".\be4v2\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-be4.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-08.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-ill-overview.html+"
fullstring = fullstring + lpath + "snip-ill-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-ill-doc.html+"
fullstring = fullstring + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring

'system product
fname = "bscan-bookeye4v3"
softprod = "bscan"
lpath = ".\be4v3\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-be4.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-08.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-ill-overview.html+"
fullstring = fullstring + lpath + "snip-ill-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-ill-doc.html+"
fullstring = fullstring + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring

'system product
fname = "bscan-bookeye3r2"
softprod = "bscan"
lpath = ".\be32\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-be3r2.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-08.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-ill-overview.html+"
fullstring = fullstring + lpath + "snip-ill-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-ill-doc.html+"
fullstring = fullstring + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring

'system product
fname = "bscan-widetek25"
softprod = "bscan"
lpath = ".\wt25\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-wt25.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-08.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-ill-overview.html+"
fullstring = fullstring + lpath + "snip-ill-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-ill-doc.html+"
fullstring = fullstring + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring