Dim sob
set sob = WScript.CreateObject("Wscript.Shell")

Function GenerateComp( fname, fullstring, path )
	dim cmd
	path = "..\"
	cmd = "Cmd /c copy /b /y "+fullstring+" "+path+fname+".html"
	'sob.popup cmd
	sob.run(cmd)
End Function

'system product family
fname = "kic"
softprod = "kic"
path = "..\generated\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + "snip-kic.html+"
fullstring = fullstring + ".\" + softprod + "\kic-family.html+"
fullstring = fullstring + ".\" + softprod + "\snip-label.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-08.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-09.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\fleet-01.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-10.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-11.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-13.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-14.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-15.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-12.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring, path

'system product
fname = "kic-bookedge"
softprod = "kic"
lpath = ".\be\"
path = "..\generated\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-be.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
'fullstring = fullstring + ".\" + lpath + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-08.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-09.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-10.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-11.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-12.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-14.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-kic-overview.html+"
fullstring = fullstring + lpath + "snip-kic-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-kic-doc.html+"
fullstring = fullstring + lpath + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring, path

'system product
fname = "kic-click-mini"
softprod = "kic"
lpath = ".\click_click-mini\"
path = "..\generated\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-clickmini.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + lpath + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-08.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-09.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-10.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-11.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-12.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-overview.html+"
fullstring = fullstring + lpath + "snip-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-doc.html+"
fullstring = fullstring + lpath + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring, path

'system product
fname = "kic-click"
softprod = "kic"
lpath = ".\click_click-mini\"
path = "..\generated\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-click.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + lpath + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-08.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-09.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-10.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-11.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-12.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-overview.html+"
fullstring = fullstring + lpath + "snip-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-doc.html+"
fullstring = fullstring + lpath + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring, path

'system product
fname = "kic-click_click-mini"
softprod = "kic"
lpath = ".\click_click-mini\"
path = "..\generated\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-click_click-mini.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + lpath + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-08.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-09.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-10.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-11.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-12.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-overview.html+"
fullstring = fullstring + lpath + "snip-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-doc.html+"
fullstring = fullstring + lpath + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring, path

'system product
fname = "kic-bookeye4"
softprod = "kic"
lpath = ".\be4\"
path = "..\generated\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-be4.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-08.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-09.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-10.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-11.html+"
fullstring = fullstring + ".\" + lpath + "\bro-con\block-12.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-kic-overview.html+"
fullstring = fullstring + lpath + "snip-kic-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-kic-doc.html+"
fullstring = fullstring + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring, path

'system product
fname = "kic-bookeye4v1"
softprod = "kic"
lpath = ".\be4v1\"
brocon_path = ".\be4\"
path = "..\generated\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-be4.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-08.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-09.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-10.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-11.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-12.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-kic-overview.html+"
fullstring = fullstring + lpath + "snip-kic-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-kic-doc.html+"
fullstring = fullstring + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring, path

'system product
fname = "kic-bookeye4v2"
softprod = "kic"
lpath = ".\be4v2\"
brocon_path = ".\be4\"
path = "..\generated\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-be4.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-08.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-09.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-10.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-11.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-12.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-kic-overview.html+"
fullstring = fullstring + lpath + "snip-kic-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-kic-doc.html+"
fullstring = fullstring + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring, path

'system product
fname = "kic-bookeye4v3"
softprod = "kic"
lpath = ".\be4v3\"
brocon_path = ".\be4\"
path = "..\generated\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-be4.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-01.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-02.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-03.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-04.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-08.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-09.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-10.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-11.html+"
fullstring = fullstring + ".\" + brocon_path + "\bro-con\block-12.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-kic-overview.html+"
fullstring = fullstring + lpath + "snip-kic-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-kic-doc.html+"
fullstring = fullstring + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring, path

'system product
fname = "kic-bookeye3r2"
softprod = "kic"
lpath = ".\be32\"
path = "..\generated\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-be3r2.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-08.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-09.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\fleet-01.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-10.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-11.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-12.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-13.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-14.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-15.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-kic-overview.html+"
fullstring = fullstring + lpath + "snip-kic-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-kic-doc.html+"
fullstring = fullstring + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring, path

'system product
fname = "kic-widetek25"
softprod = "kic"
lpath = ".\wt25\"
path = "..\generated\"
fullstring = "header.html+navbar.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-wt25.html+"
fullstring = fullstring + ".\" + softprod + "\" + softprod + "-family.html+"
'fullstring = fullstring + ".\" + softprod + "\bro-con\block-00.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-05.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-06.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-07.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-08.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-09.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-23.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\fleet-01.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-10.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-11.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-12.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-13.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-14.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-15.html+"
fullstring = fullstring + ".\" + softprod + "\bro-con\block-16.html+"
fullstring = fullstring + lpath + "snip-label.html+"
fullstring = fullstring + "snip-product-tabs-start.html+"
fullstring = fullstring + lpath + "snip-kic-overview.html+"
fullstring = fullstring + lpath + "snip-kic-features.html+"
fullstring = fullstring + lpath + "snip-techspec.html+"
fullstring = fullstring + lpath + "snip-kic-doc.html+"
fullstring = fullstring + "snip-product-compliance.html+"
fullstring = fullstring + "snip-product-tabs-end.html+"
fullstring = fullstring + "footer.html"
GenerateComp fname, fullstring, path